blog/urls.py
from django.contrib import admin
from django.urls import path

#refine imports later
from . import views

from .views import BlogListView, BlogPost

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('blog/', BlogListView.as_view(), name='blog_post_list'),
    path('<slug:slug>/', BlogPost.as_view(), name='blog_post'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
 
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=100, unique=True,)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name="blog_title")
    updated_on = models.DateTimeField(auto_now= True)
    body = models.TextField(unique=True)
    description = models.CharField(max_length=200, default="NO DESCRIPTION AVAILABLE")
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    # https://docs.djangoproject.com/en/3.1/ref/models/options/
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post


def index(request):
    # template directory for render command is defined by dirs in settings.py
    return render(request, 'index.html')

# TODO explore function based alternative
# https://www.bedjango.com/blog/class-based-views-vs-function-based-views/
class BlogListView(ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog_post_list.html'

class BlogPost(DetailView):
    model = Post
    template_name = 'blog_post.html'

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en" class="has-background-dark has-text-primary-light">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/skeleton.css'%}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
    </head>
    <body>
        <div id="body-content">
            {% block content %}
            
            {% endblock content %}
        </div>
    </body>
</html>

templates/blog_post.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}

{% block content %}
    <div class="container">
        <div class="hero">
            <div class="">
              <h1 class="site-title">Devon Ryder's Blog</h1>
              <p class="site-subtitle">Code - Linux - Technology</p>
            </div>
        </div>

        <h1>{{ post.title }}</h1>

        <p>{{ post.body | markdown | safe }}</p>

        <div class="author-panel">
            <p><strong>Devon Ryder</strong></p>
            <p>
                Information Technology Technician, Computer Programmer && Linux Enthusiast.
                Currently learning development with Django and Docker. I also have interest
                in networking and security.
            </p>
        </div>     
    </div>
    
    <!-- FOOTER SECTION -->
    <footer class="">
        <div class=""><p>&copy; - <strong>Devon Ryder</strong> - 2021.</p></div>
    </footer>

{% endblock content %}

templates/blog_post_list.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}

{% block content %}
    
    <div class="container">
        <!-- TOP BANNER HERO -->
        <div class="hero">
            <div class="">
              <h1 class="site-title">Devon Ryder's Blog</h1>
              <p class="site-subtitle">Code - Linux - Technology</p>
            </div>
        </div>

        <!-- BLOG POSTS LISTING -->
        <div class="row">
            <!-- Iterate and display blog posts from list (context) by views.py. 
            NOTE: also passed as object_list -->
            {% for post in post_list %}
                <div class="blog-post">
                    <h2 class="">{{ post.title }}</h2>
                    <p class="">Author: {{ post.author }} - Posted on: {{ post.created_on }}</p>
                    <p class="blog-post__desc">{{ post.description}}</p>
                    <p class=""><span> <a href="{% url 'blog_post' post.slug  %}" class="">Read More &rarr;</a></span></p>
                    
                </div> <!-- END blog post item-->
            {% endfor %}
        </div> <!-- END row-->

    </div> <!-- END CONTAINER -->

     <!-- FOOTER SECTION -->
     <footer class="e">
        <div class=""><p>&copy; - <strong>Devon Ryder</strong> - 2021.</p></div>
    </footer>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="page-content" aria-label="Content">
        <div class="landing-container">
            <h1 class="name"> Devon Ryder </h1>
            <h2 class="info">IT Technician | Programmer | Linux Enthusiast</h2>
            
            <div class="icons">
                <a href="https://www.linkedin.com/in/devon-ryder-9ba85483" target="_blank">
                    <img src="{% static 'img/linkedin.svg'%}" title="Linkedin Logo" alt="linkedin Logo">
                </a>
                <a href="https://github.com/DevonRyder" target="_blank">
                    <img src="{% static 'img/github.svg'%}" title="Github Logo" alt="Github Logo">
                </a>
                <a href="https://twitter.com/Ryder807" target="_blank">
                    <img src="{% static 'img/twitter.svg'%}" title="Twitter Logo" alt="Twitter Logo">
                </a>
                <a href="mailto:devon@devonryder.com">
                    <img src="{% static 'img/envelope.svg'%}" title="Devon's Email" alt="Devon's Email">
                </a>
            </div><br/>
            <a href="{% url 'blog_post_list' %}" class="">Read Blog &rarr;</a>
        </div>
    </main>
{% endblock content %}